GET http://localhost:3040/Loginuser

###

POST http://localhost:3040/Loginuser
Content-Type: application/json

{
    "name":"kyle",
    "password": "password"
}
###

POST http://localhost:3040/Signup
Content-Type: application/json

{
    "name":"kyle",
    "password": "pasword"
}